// Copyright (c) 2026 Analog Devices, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Docker support for cim.
//!
//! Generates a lightweight Dockerfile that:
//! 1. Starts from a user-supplied base image.
//! 2. Installs prerequisites (curl, ca-certificates, git).
//! 3. Creates `$HOME/bin` and `$HOME/tmp/mirror`, and puts `$HOME/bin` on PATH.
//! 4. Downloads the latest cim binary from GitHub Releases.
//! 5. Runs `cim init` to initialise the workspace inside the image.

use std::fs;
use std::io;
use std::path::Path;

/// Configuration for Dockerfile creation.
pub struct DockerfileConfig<'a> {
    /// Target name (passed to `cim init --target`).
    pub target: &'a str,
    /// Optional version / branch / tag (passed to `cim init --version`).
    pub version: Option<&'a str>,
    /// Optional manifests source URL or path (passed to `cim init --source`).
    pub source: Option<&'a str>,
    /// Docker base image, e.g. `"ubuntu:22.04"` or `"fedora:40"`.
    pub distro: &'a str,
    /// Where to write the generated Dockerfile.
    pub output_path: &'a Path,
    /// Overwrite an existing Dockerfile when `true`.
    pub force: bool,
}

/// Return the Dockerfile content as a `String` without performing any I/O.
pub fn generate_dockerfile(config: &DockerfileConfig) -> String {
    let mut f = String::new();

    // FROM -------------------------------------------------------------------
    f.push_str(&format!("FROM {}\n\n", config.distro));

    // Header comment ---------------------------------------------------------
    f.push_str("# Generated by cim\n");
    f.push_str("# Creates a ready-to-use development environment\n\n");

    // Prerequisites ----------------------------------------------------------
    // Shell-level package-manager detection so the Dockerfile works on every
    // common base image without parsing the distro string ourselves.
    f.push_str("# Install prerequisites\n");
    f.push_str("RUN if command -v apt-get >/dev/null 2>&1; then \\\n");
    f.push_str("        apt-get update && \\\n");
    f.push_str("        apt-get install -y --no-install-recommends curl ca-certificates git; \\\n");
    f.push_str("    elif command -v dnf >/dev/null 2>&1; then \\\n");
    f.push_str("        dnf install -y curl ca-certificates git-core; \\\n");
    f.push_str("    elif command -v yum >/dev/null 2>&1; then \\\n");
    f.push_str("        yum install -y curl ca-certificates git; \\\n");
    f.push_str("    elif command -v apk >/dev/null 2>&1; then \\\n");
    f.push_str("        apk add --no-cache curl ca-certificates git; \\\n");
    f.push_str("    else \\\n");
    f.push_str("        echo 'Unsupported package manager' && exit 1; \\\n");
    f.push_str("    fi\n\n");

    // Directories and PATH ---------------------------------------------------
    f.push_str("# Create required directories and configure PATH\n");
    f.push_str("ENV HOME=/root\n");
    f.push_str("RUN mkdir -p /root/bin /root/tmp/mirror\n");
    f.push_str("ENV PATH=\"/root/bin:${PATH}\"\n\n");

    // Git identity (required by cim init for applying patches etc.) --------
    f.push_str("# Configure git identity\n");
    f.push_str("RUN git config --global user.email \"none@none.com\" && \\\n");
    f.push_str("    git config --global user.name \"Docker Code in Motion\"\n\n");

    // Download cim from GitHub Releases --------------------------------------
    // Architecture is detected at Docker build time so the same Dockerfile
    // works on both x86_64 and aarch64 builder machines.
    f.push_str("# Download and install cim from GitHub releases\n");
    f.push_str("# Note: unauthenticated GitHub API calls are rate-limited to 60/hr.\n");
    f.push_str("# If building in CI, set GITHUB_TOKEN to avoid hitting the limit:\n");
    f.push_str("#   docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN ...\n");
    f.push_str("RUN set -eux; \\\n");
    f.push_str("    ARCH=$(uname -m); \\\n");
    f.push_str("    case \"${ARCH}\" in \\\n");
    f.push_str("        x86_64)  CIM_TARGET=\"x86_64-unknown-linux-musl\" ;; \\\n");
    f.push_str("        aarch64) CIM_TARGET=\"aarch64-unknown-linux-gnu\" ;; \\\n");
    f.push_str("        *) echo \"Unsupported architecture: ${ARCH}\" && exit 1 ;; \\\n");
    f.push_str("    esac; \\\n");
    f.push_str(
        "    LATEST=$(curl -fsSL \
         \"https://api.github.com/repos/analogdevicesinc/cim/releases/latest\" \\\n",
    );
    f.push_str("        | grep '\"tag_name\"' \\\n");
    f.push_str("        | sed 's/.*\"tag_name\": \"\\(.*\\)\".*/\\1/'); \\\n");
    f.push_str("    ARCHIVE=\"cim-suite-${LATEST}-${CIM_TARGET}.tar.gz\"; \\\n");
    f.push_str(
        "    curl -fsSL \
         \"https://github.com/analogdevicesinc/cim/releases/download/${LATEST}/${ARCHIVE}\" \\\n",
    );
    f.push_str("        -o /tmp/cim-suite.tar.gz; \\\n");
    f.push_str("    tar -xzf /tmp/cim-suite.tar.gz -C /tmp; \\\n");
    f.push_str(
        "    install -m 755 \
         \"/tmp/cim-suite-${LATEST}-${CIM_TARGET}/cim\" /root/bin/cim; \\\n",
    );
    f.push_str(
        "    rm -rf /tmp/cim-suite.tar.gz \
         \"/tmp/cim-suite-${LATEST}-${CIM_TARGET}\"\n\n",
    );

    // cim init ---------------------------------------------------------------
    f.push_str("# Initialise the SDK workspace\n");
    let mut init_cmd = format!("RUN cim init --target {}", config.target);
    if let Some(v) = config.version {
        init_cmd.push_str(&format!(" --version {}", v));
    }
    if let Some(s) = config.source {
        init_cmd.push_str(&format!(" --source {}", s));
    }
    init_cmd.push_str(" --full --no-sudo --yes --cert-validation=auto --symlink\n\n");
    f.push_str(&init_cmd);

    // Set working directory to the workspace ---------------------------------
    f.push_str("# Set working directory to the initialised workspace\n");
    f.push_str(&format!("WORKDIR /root/dsdk-{}\n\n", config.target));

    // Default command --------------------------------------------------------
    f.push_str("# Default command\n");
    f.push_str("CMD [\"/bin/bash\"]\n");

    f
}

/// Write a Dockerfile to `config.output_path`.
///
/// Returns `Err` with `io::ErrorKind::AlreadyExists` if the file exists and
/// `config.force` is `false`.
pub fn create_dockerfile(config: &DockerfileConfig) -> io::Result<()> {
    if config.output_path.exists() && !config.force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!(
                "Dockerfile already exists at '{}'. Use --force to overwrite.",
                config.output_path.display()
            ),
        ));
    }

    if let Some(parent) = config.output_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }

    let content = generate_dockerfile(config);
    fs::write(config.output_path, content)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_generate_dockerfile_from_directive() {
        let config = DockerfileConfig {
            target: "my-target",
            version: None,
            source: None,
            distro: "ubuntu:22.04",
            output_path: Path::new("Dockerfile"),
            force: false,
        };
        let out = generate_dockerfile(&config);
        assert!(out.starts_with("FROM ubuntu:22.04\n"));
        assert!(out.contains(
            "cim init --target my-target --full --no-sudo --yes --cert-validation=auto --symlink"
        ));
        assert!(out.contains("WORKDIR /root/dsdk-my-target"));
        assert!(out.contains("CMD [\"/bin/bash\"]"));
    }

    #[test]
    fn test_generate_dockerfile_with_version_and_source() {
        let config = DockerfileConfig {
            target: "optee-qemu-v8",
            version: Some("main"),
            source: Some("https://github.com/org/manifests.git"),
            distro: "fedora:40",
            output_path: Path::new("Dockerfile"),
            force: false,
        };
        let out = generate_dockerfile(&config);
        assert!(out.starts_with("FROM fedora:40\n"));
        assert!(out.contains("--target optee-qemu-v8"));
        assert!(out.contains("--version main"));
        assert!(out.contains("--source https://github.com/org/manifests.git"));
        assert!(out.contains("--full --no-sudo --yes --cert-validation=auto --symlink"));
    }

    #[test]
    fn test_generate_dockerfile_downloads_cim() {
        let config = DockerfileConfig {
            target: "t",
            version: None,
            source: None,
            distro: "ubuntu:22.04",
            output_path: Path::new("Dockerfile"),
            force: false,
        };
        let out = generate_dockerfile(&config);
        assert!(out.contains("api.github.com/repos/analogdevicesinc/cim/releases/latest"));
        assert!(out.contains("cim-suite-${LATEST}-${CIM_TARGET}.tar.gz"));
        assert!(out.contains("/root/bin/cim"));
        assert!(out.contains("ENV PATH=\"/root/bin:${PATH}\""));
        assert!(out.contains("/root/tmp/mirror"));
    }

    #[test]
    fn test_create_dockerfile_writes_file() {
        let dir = tempdir().unwrap();
        let out = dir.path().join("Dockerfile");
        let config = DockerfileConfig {
            target: "t",
            version: None,
            source: None,
            distro: "ubuntu:22.04",
            output_path: &out,
            force: false,
        };
        create_dockerfile(&config).unwrap();
        assert!(out.exists());
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.starts_with("FROM ubuntu:22.04\n"));
    }

    #[test]
    fn test_create_dockerfile_no_overwrite_without_force() {
        let dir = tempdir().unwrap();
        let out = dir.path().join("Dockerfile");
        fs::write(&out, "existing").unwrap();
        let config = DockerfileConfig {
            target: "t",
            version: None,
            source: None,
            distro: "ubuntu:22.04",
            output_path: &out,
            force: false,
        };
        let result = create_dockerfile(&config);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err().kind(), io::ErrorKind::AlreadyExists);
        // Original file must not be modified
        assert_eq!(fs::read_to_string(&out).unwrap(), "existing");
    }

    #[test]
    fn test_create_dockerfile_force_overwrites() {
        let dir = tempdir().unwrap();
        let out = dir.path().join("Dockerfile");
        fs::write(&out, "old content").unwrap();
        let config = DockerfileConfig {
            target: "t",
            version: None,
            source: None,
            distro: "alpine:3.19",
            output_path: &out,
            force: true,
        };
        create_dockerfile(&config).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.starts_with("FROM alpine:3.19\n"));
    }
}
